/* 
 * engine/itemgen.ts
 *
 * This file contains the addEntities function, which takes in a reference to the
 * game object and adds different entities like food and enemies into the map 
 * (a flat array of rooms generated by the generateMap function in mapgen.ts) 
 * based on what level the player is on.
 */

import * as components from "./components";
import { randInt, Rect } from "./helpers";
import type Game from "./main";
import { newItemEntity } from "./templates/item";
import { newZombieEntity } from "./templates/zombie";

export const addEntities = (game: Game): void => {
    for (const room of game.rooms) { // for each room in the map
        // 5-10 logs in each room
        for (let i = 0; i < randInt(5, 10); i++) {
            newItemEntity(
                game,
                room,
                game.getImage("items"),
                new Rect(0, 0, 16, 16),
                new Rect(1, 1, game.tileSize - 1, game.tileSize - 1)
            );
        }

        for (let i = 0; i < Math.round(game.level / 3); i++) {
            newZombieEntity(game, room);
        }
    }

    // add a stick in the room the player starts in

    const stick = newItemEntity(
        game,
        game.roomAt(game.playerRoomPos),
        game.getImage("items"),
        new Rect(0, 16, 16, 16)
    );

    game.ecs.addComponent(stick, components.WeaponComponent, [5]);

};